import './globals.css';

import { Inter } from 'next/font/google';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const fontSans = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${fontSans.variable} [color-scheme:dark]`}>
      <body className="bg-slate-900 font-sans text-slate-50 antialiased">
        {children}
      </body>
    </html>
  );
}
